### ISSUE TITLE
clarify copyright year information

### ISSUE THREAD

**Issue by alexanderkjall** [mexus/display-error-chain#2]
Hi, I'm trying to package this project for Debian and would like some help with the copyright documentation.

The first commit to this project was in 2021 when I look in git, but the license file says 2016 here: https://github.com/mexus/display-error-chain/blob/master/LICENSE-MIT#L1

Is that just a copy-and-paste error, or is 2016 the correct date?

**Comment by mexus** [comment]
> Hi, I'm trying to package this project for Debian and would like some help with the copyright documentation.
> 
> The first commit to this project was in 2021 when I look in git, but the license file says 2016 here: https://github.com/mexus/display-error-chain/blob/master/LICENSE-MIT#L1
> 
> Is that just a copy-and-paste error, or is 2016 the correct date?

Hi @alexanderkjall and sorry for such a late reply! Totally missed the notification >_<

Yeah, it's definitely a copy-paste error. Will make a PR with the correct year(s). Thanks!

**Comment by mexus** [comment]
Updated the license files, updated crate version to 0.2.1, published it on crates.io
