### ISSUE TITLE
Feature request: Implement Debug trait on DisplayErrorChain

### ISSUE THREAD

**Issue by JohnstonJ** [mexus/display-error-chain#3]
I want to use the `DisplayErrorChain` struct with the [`displays_as`](https://docs.rs/googletest/0.12.0/googletest/matchers/fn.displays_as.html) matcher in googletest.

But it's not directly possible, because `DisplayErrorChain` does not implement the `Debug` trait, which is required to be implemented by an assertion subject.  In my case, as a workaround, I can call `to_string` and just have the assertion compare strings.

In general, however, I would imagine there are other situations where one might want to use the `Debug` trait.  Is it possible that `DisplayErrorChain` could implement the `Debug` trait?

**Comment by mexus** [comment]
Sure thing, no problem!

**Comment by mexus** [comment]
I added derives for some common traits and published the updated version. The `Debug` trait is now implemented when the underlying `Error` type also implements it:
https://docs.rs/display-error-chain/latest/display_error_chain/struct.DisplayErrorChain.html#impl-Debug-for-DisplayErrorChain%3CE%3E
